name: Openwrt Packages Build Bot
on:
  push:
    branches: main
    paths:
      - '.github/workflows/build-packages-release.yml'
      - 'patch.sh'
      - 'do_not_build'
      - 'packages/**'
      - '!packages/**/github/workflows/**'
      - '!packages/**/README*'
      - '!packages/**/.gitignore'
      - '!packages/**/LICENSE'
      - '!packages/**/LICENSES'

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53-v22.03.4
          - aarch64_cortex-a72-v22.03.4
          - aarch64_generic-v22.03.4
          - arc_archs-v22.03.4
          - arm_arm1176jzf-s_vfp-v22.03.4
          - arm_arm926ej-s-v22.03.4
          - arm_cortex-a15_neon-vfpv4-v22.03.4
          - arm_cortex-a5_vfpv4-v22.03.4
          - arm_cortex-a7-v22.03.4
          - arm_cortex-a7_neon-vfpv4-v22.03.4
          - arm_cortex-a7_vfpv4-v22.03.4
          - arm_cortex-a8_vfpv3-v22.03.4
          - arm_cortex-a9-v22.03.4
          - arm_cortex-a9_neon-v22.03.4
          - arm_cortex-a9_vfpv3-d16-v22.03.4
          - arm_fa526-v22.03.4
          - arm_mpcore-v22.03.4
          - arm_xscale-v22.03.4
          - i386_pentium-mmx-v22.03.4
          - i386_pentium4-v22.03.4
          - mips64_octeonplus-v22.03.4
          - mips_24kc-v22.03.4
          - mips_4kec-v22.03.4
          - mips_mips32-v22.03.4
          - mipsel_24kc-v22.03.4
          - mipsel_24kc_24kf-v22.03.4
          - mipsel_74kc-v22.03.4
          - mipsel_mips32-v22.03.4
          - powerpc_464fp-v22.03.4
          - powerpc_8540-v22.03.4
          - x86_64-v22.03.4
          - aarch64_cortex-a53-v21.02.5
          - aarch64_cortex-a72-v21.02.5
          - aarch64_generic-v21.02.5
          - arc_arc700-v21.02.5
          - arc_archs-v21.02.5
          - arm_arm1176jzf-s_vfp-v21.02.5
          - arm_arm926ej-s-v21.02.5
          - arm_cortex-a15_neon-vfpv4-v21.02.5
          - arm_cortex-a5_vfpv4-v21.02.5
          - arm_cortex-a7-v21.02.5
          - arm_cortex-a7_neon-vfpv4-v21.02.5
          - arm_cortex-a8_vfpv3-v21.02.5
          - arm_cortex-a9-v21.02.5
          - arm_cortex-a9_neon-v21.02.5
          - arm_cortex-a9_vfpv3-d16-v21.02.5
          - arm_fa526-v21.02.5
          - arm_mpcore-v21.02.5
          - arm_xscale-v21.02.5
          - i386_pentium-mmx-v21.02.5
          - i386_pentium4-v21.02.5
          - mips64_octeonplus-v21.02.5
          - mips_24kc-v21.02.5
          - mips_4kec-v21.02.5
          - mips_mips32-v21.02.5
          - mipsel_24kc-v21.02.5
          - mipsel_24kc_24kf-v21.02.5
          - mipsel_74kc-v21.02.5
          - mipsel_mips32-v21.02.5
          - powerpc_464fp-v21.02.5
          - powerpc_8540-v21.02.5
          - x86_64-v21.02.5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Prepare feeds
        run: |
          ./patch.sh ${{ matrix.arch }}
          PACKAGES=$(ls packages | sed 's/\///g')
          echo "$PACKAGES" > 1.txt
          sort 1.txt -o 1.txt
          sort do_not_build -o do_not_build
          comm -23 1.txt do_not_build > 2.txt
          PACKAGES=$(cat 2.txt)
          PACKAGES=$(echo "$PACKAGES" | tr '\n' ' ')
          echo "PACKAGES=${PACKAGES}" >> $GITHUB_ENV
          find . -name "Makefile" -type f -exec cat {} \;

      - name: Build
        uses: ekkog/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          IGNORE_ERRORS: 1
          NO_SHFMT_CHECK: 1
          V: 99
          PACKAGES: ${{ env.PACKAGES }}


      - name: List files
        run: |
          ls -R bin/

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          ARCH=$(echo $ARCH | sed 's/-v/-/g')
          BRANCH="${ARCH::-2}"
          cd bin/packages/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH
